# Pi-hole local DNS records for reverse-proxied apps.
# Update IP if SERVER_IP changes.
address=/home.local/10.10.2.200
address=/dashy.home.local/10.10.2.200
address=/vscode.home.local/10.10.2.200
address=/portainer.home.local/10.10.2.200
address=/glances.home.local/10.10.2.200
address=/nextcloud.home.local/10.10.2.200
address=/jellyfin.home.local/10.10.2.200
address=/qbittorrent.home.local/10.10.2.200
address=/immich.home.local/10.10.2.200
address=/files.home.local/10.10.2.200
